### ISSUE TITLE
Have not found any proper Android SDK documentation and Apis.

### ISSUE THREAD

**Issue by MohsinIkram-Auxilium** [onfleet/android-driver-sdk-example#1]
Hi,
I want to integrate your SDK into our Android App but i have not found any proper Android SDK documentation and Apis.
Can you please provide me the resources how can i implement this in our app and which type of Apis you are providing to Android App.
Need your swift response.
Thanks

**Comment by polivmi1** [comment]
Hello @MohsinIkram-Auxilium,
to use the SDK you will have to speak with your contact at Onfleet or write to support@onfleet.com and they will let you know the next steps. The documentation is part of the package hosted at Maven. To see it, you will need to open the Javadoc file at https://repo1.maven.org/maven2/com/onfleet/driver/0.11.1/
Let me know if you have any other questions.
